import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
    fr: {
        'dashboard': 'Tableau de bord',
        'contacts': 'Contacts',
        'members': 'Membres',
        'visitors': 'Visiteurs',
        'organizations': 'Organisations',
        'events': 'Événements',
        'groups': 'Groupes',
        'finances': 'Finances',
        'income': 'Revenus',
        'expenses': 'Dépenses',
        'budgets': 'Budgets',
        'sunday_school': 'École du Dimanche',
        'overview': 'Vue d\'ensemble',
        'classes': 'Classes',
        'class_details': 'Détails de la classe',
        'participant_code': 'Code du participant',
        'participant_name': 'Nom du participant',
        'member_role': 'Rôle du membre',
        'criteria': 'Critères',
        'active_only': 'Actifs Uniquement',
        'monitors': 'Moniteurs',
        'attendance_rate': 'Taux de présence',
        'new_members': 'Nouveaux membres',
        'transitions_due': 'Transitions en attente',
        'monitor_coverage': 'Couverture des moniteurs',
        'reports_status': 'État des rapports',
        'recent_activity': 'Activité récente',
        'near_transition': 'Près de la transition',
        'recommended_class': 'Classe recommandée',
        'transition_reason': 'Raison',
        'total_active_classes': 'Classes actives',
        'attendance_trend': 'Tendance de présence',
        'class_distribution': 'Répartition des classes',
        'alerts_notifications': 'Alertes et Notifications',
        'pending_reports': 'Rapports en attente',
        'weekly_report': 'Rapport Hebdomadaire',
        'general_info': 'Informations Générales',
        'meeting_date': 'Date de la Rencontre',
        'meeting_title': 'Nom de la rencontre',
        'lesson_details': 'Détails de la Leçon',
        'lesson_title_form': 'La leçon vue',
        'total_lesson_points': 'Nombre de points de la leçon',
        'covered_lesson_points': 'Nombre de points vus',
        'golden_text': 'Texte d\'or',
        'attendance_list': 'Liste des Participants',
        'lesson_metrics': 'Indicateurs de Participation',
        'bible_count': 'Nombre de bibles',
        'hymnal_count': 'Nombre de chants',
        'offering_collected': 'Quantité d\'offrande ramassée',
        'feedback_and_expectations': 'Feedback et Attentes',
        'monitor_notes': 'Notes du moniteur concernant la leçon',
        'monitor_expectations': 'Attentes du moniteur',
        'participant_expectations': 'Attentes des participants',
        'submit_report': 'Soumettre le Rapport',
        'spiritual_progress': 'Progrès Spirituel',
        'presence_list': 'Liste de Présence',
        'new_weekly_report': 'Nouveau Rapport Hebdomadaire',
        'report_submitted_success': 'Rapport soumis avec succès !',
        'reports': 'Rapports',
        'reports_history': 'Historique des Rapports',
        'no_reports_found': 'Aucun rapport disponible',
        'lesson_title': 'Titre de la Leçon',
        'lesson_completion': 'Complétion de la Leçon',
        'participation_metrics': 'Indicateurs de Participation',
        'feedback': 'Feedback & Observations',
        'submitted_by': 'Soumis par',
        'report_not_found': 'Rapport non trouvé',
        'offering': 'Offrande',
        'new_class': 'Nouvelle Classe',
        'edit_class': 'Modifier la classe',
        'create_new_class': 'Créer une nouvelle classe',
        'class_name': 'Nom de la classe',
        'age_group': 'Groupe d\'âge',
        'min_age': 'Âge Minimum',
        'max_age': 'Âge Maximum',
        'distribution_by_class': 'Répartition par Classe',
        'assign_monitor': 'Assigner un Moniteur',
        'choose_member': 'Choisir un membre',
        'monitor_assigned_success': 'Moniteur assigné avec succès',
        'class_created_success': 'Classe créée avec succès',
        'class_updated_success': 'Classe mise à jour avec succès',
        'baptismal_status': 'Statut Baptismal',
        'baptized': 'Baptisé',
        'not_baptized': 'Non baptisé',
        'candidate': 'Candidat au baptême',
        'adherent': 'Adhérent',
        'transferred': 'Transféré',
        'affiliated': 'Affilié',
        'child': 'Enfant',
        'other': 'Autre',
        'search_classes': 'Rechercher une classe...',
        'no_match_search': 'Aucune classe ne correspond à votre recherche.',
        'no_classes_desc': 'Commencez par créer votre première classe d\'école du dimanche.',
        'any': 'Peu importe',
        'inventory': 'Inventaire',
        'ceremonies': 'Cérémonies',
        'settings': 'Paramètres',
        'logout': 'Déconnexion',
        'hello': 'Bonjour',
        'admin': 'Admin',
        'configuration_required': 'Configuration Requise',
        'setup_msg': 'Avant de commencer à gérer votre église, vous devez configurer les informations de base.',
        'setup_btn': 'Configurer maintenant',
        'total_members': 'Total Membres',
        'new_member': 'Nouveau membre',
        'search': 'Rechercher',
        'status': 'Statut',
        'active': 'Actif',
        'inactive': 'Inactif',
        'country': 'Pays',
        'category': 'Catégorie',
        'reset': 'Réinitialiser',
        'export_pdf': 'Exporter en PDF',
        'export_excel': 'Exporter en Excel',
        'export': 'Exporter',
        'export_options': 'Options d\'exportation',
        'select_export_fields': 'Sélectionnez les champs à inclure dans votre rapport.',
        'all': 'Tout',
        'age': 'Âge',
        'email': 'Email',
        'income_overview': 'Aperçu des Revenus',
        'distribution_by_type': 'Distribution par Type',
        'recent_transactions': 'Transactions Récentes',
        'view_all': 'Voir tout',
        'income_vs_expenses': 'Revenus vs Dépenses',
        'total_income': 'Total Revenus',
        'total_expenses': 'Total Dépenses',
        'balance': 'Solde',
        'transactions': 'Transactions',
        'new_donation': 'Nouveau Don',
        'amount': 'Montant',
        'date': 'Date',
        'member': 'Membre',
        'type': 'Type',
        'payment_method': 'Mode de Paiement',
        'note': 'Note',
        'save': 'Enregistrer',
        'cancel': 'Annuler',
        'loading': 'Chargement...',
        'no_data': 'Aucune donnée trouvée.',
        'total_revenue': 'Revenu Total',
        'this_month_short': 'ce mois-ci',
        'monthly_analysis': 'ANALYSE MENSUELLE',
        'growth_insight': 'Croissance positive ce mois-ci',
        'view_details': 'Voir détails',
        'anonymous': 'Anonyme',
        'confirmed': 'Confirmé',
        'currency': 'Devise',
        'select_member_placeholder': 'Sélectionner un membre (Anonyme par défaut)',
        'no_results': 'Aucun résultat',
        'first_name': 'Prénom',
        'last_name': 'Nom',
        'gender_label': 'Sexe',
        'masculine': 'Masculin',
        'feminine': 'Féminin',
        'birth_date': 'Date de naissance',
        'marital_status_label': 'État Civil',
        'single': 'Célibataire',
        'married': 'Marié(e)',
        'divorced': 'Divorcé(e)',
        'widowed': 'Veuf/Veuve',
        'contact_info': 'Coordonnées',
        'phone': 'Téléphone',
        'address': 'Adresse',
        'city': 'Ville',
        'nif_cin_label': 'NIF / CIN',
        'photo': 'Photo',
        'upload_file': 'Uploader',
        'use_url': 'Utiliser URL',
        'edit_member': 'Modifier le membre',
        'fill_info_desc': 'Remplissez les informations ci-dessous',
        'identity_personnel': 'Identité & Personnel',
        'select': 'Sélectionner',
        'recent_members_added': 'Derniers membres ajoutés',
        'visitors_desc': 'Gérez les visiteurs et leur intégration dans la communauté.',
        'full_name': 'Nom Complet',
        'status_integrated': 'Intégration',
        'no_visitors': 'Aucun visiteur trouvé.',
        'visitor_info_desc': 'Informations de base sur le visiteur',
        'status_integrated_label': 'Intégré',
        'status_contacted_label': 'Contacté',
        'status_visited_label': 'Visité',
        'management_desc': 'Gérez les organisations partenaires et affiliées.',
        'new_org': 'Nouvelle Organisation',
        'edit_org': 'Modifier l\'Organisation',
        'org_info_desc': 'Détails et classification de l\'organisation',
        'identification_classification': 'Identification & Classification',
        'org_name': 'Nom de l\'Organisation',
        'org_name_placeholder': 'Ex: Fondation, École, ONG...',
        'select_category': 'Sélectionner une catégorie',
        'contact_location': 'Contact & Localisation',
        'official_email': 'Email Officiel',
        'address_placeholder': 'Adresse complète...',
        'no_orgs': 'Aucune organisation trouvée.',
        'org_list_title': 'Liste des Organisations',
        'quick_insight': 'Aperçu rapide',
        'system_health': 'Santé du système',
        'users_online': 'Utilisateurs en ligne',
        'server_load': 'Charge serveur',
        'last_backup': 'Dernière sauvegarde',
        'take_action': 'Agir maintenant',
        'deposited_on_account': 'Encaissé sur compte ?',
        'select_account_placeholder': 'Sélectionner le compte...',
        'no_account_found_currency': 'Aucun compte trouvé pour la devise',
        'deposit_date_label': "Date d'encaissement",
        'deposited_by': 'Encaissé par',
        'confirm_donation': 'Confirmer le Don',
        'data_load_error': 'Impossible de charger les données. Vérifiez que le serveur est démarré. ',
        'account_created_success': 'Compte créé avec succès !',
        'creation_error': 'Erreur lors de la création',
        'select_bank_account_error': 'Veuillez sélectionner un compte bancaire.',
        'select_donations_error': 'Veuillez sélectionner au moins une donation à déposer.',
        'select_date_error': "Veuillez sélectionner la date d'encaissement.",
        'select_depositor_error': 'Veuillez sélectionner la personne qui a effectué le dépôt.',
        'overview': "Vue d'ensemble",
        'accounts_and_treasury': 'Comptes & Trésorerie',
        'administrator': 'Administrateur',
        'cancel_btn': 'Annuler',
        'update_btn': 'Mettre à jour',
        'save_btn': 'Enregistrer',
        'saving': 'Enregistrement...',
        'elyonsys_360': 'ELYONSYS 360',
        'error_saving': "Erreur lors de l'enregistrement",
        'first_name_placeholder': 'Ex: Jean',
        'last_name_placeholder': 'Ex: Dupont',
        'optional': 'Optionnel',
        'error_saving_expense': "Erreur lors de l'enregistrement de la dépense",
        'insufficient_funds': 'Fonds insuffisants',
        'fonds_insufficient_disp': 'Fonds insuffisants. Disponible: ',
        'error_creating_budget': 'Erreur lors de la création du budget',
        'budgets_desc': 'Gestion et suivi des enveloppes budgétaires.',
        'full_list': 'Liste Complète',
        'export_list': 'Exporter la liste',
        'search_budget': '🔍 Rechercher un budget...',
        'all_statuses': 'Tous les statuts',
        'consumed': 'Consommé',
        'no_budgets_found': 'Aucun budget trouvé pour ces critères.',
        'allocate_funds': "Allocation des fonds de l'église",
        'source_account': 'Compte Source',
        'available_for_this_budget': 'Disponible pour ce budget',
        'budget_name_label': 'Nom du budget',
        'allocated_amount': 'Montant alloué',
        'bank_account_source': 'Compte Bancaire Source',
        'select_source_account': 'Sélectionner le compte source',
        'start_date': 'Date de début',
        'end_date': 'Date de fin',
        'budget_objectives_placeholder': 'Objectifs de ce budget...',
        'create_budget_btn': 'Créer le budget',
        'detailed_report': 'Rapport Détaillé',
        'print_pdf': 'Imprimer / PDF',
        'excel': 'Excel',
        'budget_total': 'Budget Total',
        'expenses_detail': 'Détail des Dépenses',
        'loading_expenses': 'Chargement des dépenses...',
        'no_expenses_found': 'Aucune dépense enregistrée sur ce budget.',
        'total_expenses_label': 'Total Dépenses:',
        'prepared_by': 'Préparé par :',
        'responsible_pastor': 'Responsable / Pasteur :',
        'generated_by_on': 'Généré par ElyonSys 360 le ',
        'no_active_budgets': 'Aucun budget actif pour le moment.',
        'active_budgets': 'Budgets Actifs',
        'view_report': 'Voir le rapport',
        'used': 'Utilisé',
        'remaining_text': 'restant',
        'period': 'Période',
        'report': 'Rapport',
        'expenses_desc': "Suivez les sorties d'argent et gérez vos coûts.",
        'budget_expenses_desc': "Liste des dépenses imputées à ce budget spécifique.",
        'view_all_expenses': 'Voir toutes les dépenses',
        'new_expense': 'Nouvelle Dépense',
        'no_expenses_for_budget': 'Aucune dépense enregistrée sur ce budget.',
        'no_category': 'Sans catégorie',
        'out_of_budget': 'Hors Budget',
        'new_expense_desc': "Enregistrement d'une sortie de fonds",
        'available_in_budget': 'Disponible dans ce budget',
        'expense_reason_label': 'Motif de la dépense',
        'expense_reason_placeholder': 'Ex: Facture électricité, Achat chaises...',
        'impute_to_budget': 'Imputer au budget',
        'select_budget': 'Sélectionner un budget',
        'funds_deduction_notice': 'Les fonds seront déduits du compte source du budget.',
        'category_placeholder': 'Ex: Administration, Social...',
        'budget_exceeded_error': 'Le montant dépasse le budget. Action impossible.',
        'validate_expense_btn': 'Valider la Dépense',
        'contacts_dashboard': 'Tableau de bord des contacts',
        'overview_stats': "Vue d'ensemble et statistiques",
        'search_member': 'Rechercher un membre',
        'church_growth': "Croissance de l'église",
        'last_6_months': '6 derniers mois',
        'by_gender': 'Par sexe',
        'men': 'Hommes',
        'women': 'Femmes',
        'by_category': 'Par catégorie',
        'unclassified': 'Non classifié',
        'by_status': 'Par statut',
        'traveling': 'En déplacement',
        'deceased': 'Décédé',
        'transferred': 'Transféré',
        'abandoned': 'Abandonné',
        'recent_additions': 'Derniers ajouts',
        'view_all_members': 'Voir tous les membres',
        'error_saving_note': "Erreur lors de la sauvegarde de la note",
        'error_updating_photo': "Erreur lors de la mise à jour de la photo",
        'error_updating_status': "Erreur lors de la mise à jour du statut",
        'error_updating_type': "Erreur lors de la mise à jour du type",
        'member_not_found': 'Membre introuvable',
        'back': 'Retour',
        'view_large': 'Voir en grand',
        'change_photo': 'Changer la photo',
        'modify_summary': 'Modifier le résumé',
        'add_summary_note': 'Ajouter un résumé',
        'modify': 'Modifier',
        'mark_as': 'Marquer comme...',
        'change_type': 'Changer de type',
        'no_types_available': 'Aucun type disponible',
        'change_status': 'Changer le statut',
        'passing_status_to': 'Passage du statut vers',
        'effective_date': "Date d'effet",
        'confirm': 'Confirmer',
        'passing_category_to': 'Passage de la catégorie vers',
        'info': 'Info',
        'personal_information': 'Information Personnelle',
        'gender': 'Sexe',
        'birth': 'Naissance',
        'civil_status': 'État Civil',
        'nif_cin': 'NIF / CIN',
        'age': 'Âge',
        'years': 'ans',
        'geo': 'Géo',
        'contact_localization': 'Contact & Localisation',
        'no_number': 'Aucun numéro',
        'no_address_recorded': 'Aucune adresse enregistrée',
        'history_activities': 'Historique & Activités',
        'relationships_network': 'Relations & Réseau',
        'donations_history': 'Historique des Dons',
        'payment_date': 'Date de versement',
        'donation_type': 'Type de Don',
        'total_amount': 'Montant total',
        'no_donations_recorded': 'Aucun don enregistré',
        'membership_groups': "Groupes d'appartenance",
        'no_groups_found': 'Aucun groupe trouvé',
        'ceremonies_attended': 'Cérémonies participées',
        'no_ceremonies_recorded': 'Aucune cérémonie enregistrée',
        'tithe_regulator': 'Régulateur de Dîmes',
        'events_attended': 'Événements participés',
        'no_participation_recorded': 'Aucune participation enregistrée',
        'status_history': 'Historique des statuts',
        'changed_by': 'Modifié par',
        'system': 'Système',
        'no_history_available': 'Aucun historique disponible',
        'category_history': 'Historique de catégorie',
        'close': 'Fermer',
        'good_morning': 'Bonjour',
        'good_afternoon': 'Bon après-midi',
        'good_evening': 'Bonsoir',
        'dashboard_welcome_desc': "Voici un aperçu de l'activité de votre communauté aujourd'hui.",
        'insight_desc': 'Vous avez des activités à vérifier cette semaine.',
        '2h_ago': 'Il y a 2h',
        'management_desc': 'Gestion des entités externes',
        'new_org': 'Organisation',
        'org_list_title': 'Liste des Organisations',
        'no_orgs': 'Aucune organisation enregistrée.',
        'edit_org': "Modifier l'organisation",
        'org_info_desc': 'Gérez les informations et les contacts de la structure.',
        'identification_classification': 'Identification & Classification',
        'org_name': "Nom de l'Organisation",
        'org_name_placeholder': 'Ex: Église de la Prophétie',
        'select_category': 'Sélectionner...',
        'official_email': 'Email Officiel',
        'address_hq': 'Adresse Siège',
        'address_placeholder': 'Rue, Ville, Pays',
        'notes_placeholder': 'Informations complémentaires...',
        'visitors_desc': 'Gérez les personnes qui visitent votre église.',
        'new_visitor': 'Nouveau Visiteur',
        'full_name': 'Nom Complet',
        'status_integrated': 'Intégration',
        'status_contacted': 'Contacté',
        'no_visitors': 'Aucun visiteur enregistré.',
        'visitor_info_desc': 'Ajoutez un nouveau visiteur à votre base de données.',
        'note_placeholder_summary': 'Notes de résumé...',
        'member_details': 'Détails du membre',
        'baptized': 'Baptisé',
        'category_changed_on': 'Catégorie modifiée le',
        'no_recent_members': 'Aucun membre récent.',
        'loading_config': 'Chargement de la configuration...',
        'church_settings_website': "Paramètres de l'église - Website",
        'identity_appearance_comm': 'Identité, Apparence & Communication',
        'basic_info': 'Informations de base',
        'identity_global_desc': 'Identité et description globale',
        'church_name': "Nom de l'Église",
        'church_name_placeholder': "Ex: Église de la Prophétie",
        'acronym_label': 'Sigle / Acronyme',
        'subdomain_label': 'Sous-domaine (Identifiant Unique)',
        'owner_email_label': 'Email du Propriétaire (Admin)',
        'description_who_we_are': 'Description (Qui sommes-nous ?)',
        'appearance': 'Apparence',
        'visual_identity_desc': 'Visuel et identité de la plateforme',
        'hero_image_label': "Image Hero (Fond d'accueil)",
        'hero_image_placeholder': "URL de l'image ou téléchargez-en une...",
        'upload': 'Télécharger',
        'hero_image_hint': 'Recommandé : 1920x1080px, moins de 5MB',
        'current_preview': 'Aperçu Actuel',
        'remove_image': "Retirer l'image",
        'mission_title_label': 'Titre ou Résumé de la Mission',
        'mission_title_placeholder': 'Ex: Porter la Lumière du monde.',
        'mission_desc_label': 'Description de la Mission',
        'mission_bg_image': 'Image de fond (Mission)',
        'vision_title_label': 'Titre ou Résumé de la Vision',
        'vision_title_placeholder': 'Ex: Bâtir une génération unie par la foi.',
        'vision_desc_label': 'Description de la Vision',
        'vision_bg_image': 'Image de fond (Vision)',
        'our_values': 'Nos Valeurs',
        'values_placeholder': 'Liste de vos valeurs (ex: Amour, Foi, Excellence)...',
        'values_image': 'Image Valeurs',
        'design_tip': 'Conseil Design',
        'values_image_tip': "L'image des valeurs apparaîtra à côté du texte sur votre page d\\'accueil. Utilisez une image qui illustre l'esprit de votre communauté ou un montage de vos activités clés.",
        'pastoral_team': 'Équipe Pastorale',
        'leadership_members': 'Membres de la direction',
        'pastoral_team_json_desc': 'Format JSON pour lister votre équipe. Bientôt, une interface simplifiée sera disponible.',
        'service_schedules': 'Horaires des Services',
        'weekly_appointments': 'Vos rendez-vous hebdomadaires',
        'schedules_json_desc': 'Définissez vos horaires pour affichage sur le site public. (Obligatoire pour le site public)',
        'social_links_and_links': 'Réseaux Sociaux & Liens',
        'online_presence_live': 'Présence en ligne et services en direct',
        'platform_name_placeholder': 'Ex: YouTube, Facebook',
        'live_service_link_label': 'Lien du Service en Direct (URL complète)',
        'url_placeholder': 'https://www.youtube.com/live/...',
        'copy': 'COPIER',
        'paste': 'COLLER',
        'link_copied': 'Lien copié !',
        'link_pasted': 'Lien collé !',
        'paste_error': 'Impossible de lire le presse-papier. Collez manuellement avec Ctrl+V.',
        'live_link_hint': 'Si ce lien est rempli, un bouton "En Ligne" apparaîtra sur votre page d\'accueil publique.',

        'recent_activities': 'Activités Récentes',
        'public_site_news': 'Actualités du site public',
        'activities_json_desc': 'Format JSON pour lister vos activités. Bientôt, une interface de gestion simplifiée sera disponible.',
        'contact_location': 'Contact & Localisation',
        'coords_physical_address': 'Coordonnées et adresse physique',
        'full_address': 'Adresse complète',
        'address_placeholder_miracles': 'Ex: 123, Rue des Miracles',
        'city_placeholder_pap': 'Ex: Port-au-Prince',
        'contact_email': 'Email de contact',
        'save_section': 'Enregistrer cette section',
        'finance_settings': 'Paramètres Finances',
        'currencies_donations_accounting': 'Monnaies, Dons & Comptabilité',
        'currencies_and_money': 'Devises & Monnaies',
        'accepted_currencies_management': 'Gestion des monnaies acceptées',
        'mandatory_currencies_error': 'HTG et USD sont obligatoires et ne peuvent être supprimés.',
        'cannot_delete_currency_balance': 'Impossible de supprimer : Balance non nulle.',
        'currency_code_placeholder': 'Code (ex: EUR, CAD)',
        'add_currency': 'Ajouter la monnaie',
        'donation_types_settings': 'Types de Dons',
        'custom_categories': 'Catégories personnalisées',
        'donation_category_placeholder': 'Nom de la catégorie (ex: Construction)',
        'new_type': 'Nouveau Type',
        'payment_methods_settings': 'Méthodes de Paiement',
        'accepted_payment_methods': 'Moyens de paiement acceptés',
        'payment_method_placeholder': 'Nom de la méthode (ex: MonCash)',
        'new_method': 'Nouvelle Méthode',
        'users_roles_management': 'Gestion des Utilisateurs & Rôles',
        'roles_permissions_desc': 'Créez des rôles personnalisés avec des permissions spécifiques',
        'permissions_granted': 'permissions accordées',
        'new_role': 'Nouveau Rôle',
        'create_role': 'Créer un Rôle',
        'role_name_label': 'Nom du Rôle (ex: Secrétaire)',
        'role_name_placeholder': 'Entrez le nom du rôle...',
        'permissions_access': 'Permissions & Accès',
        'save_role': 'Enregistrer le Rôle',
        'contact_classification': 'Classification des Contacts',
        'custom_types_subtypes': 'Types & Sous-types personnalisés',
        'global_types': 'Types globaux',
        'new_type_placeholder': 'Nouveau type (ex: Partenaire)',
        'add': 'Ajouter',
        'contact_subtypes': 'Sous-types de contacts',
        'no_subtypes_defined': 'Aucun sous-type défini',
        'add_subtype': 'Ajouter un sous-type',
        'select_type_placeholder': 'Sélectionner un Type...',
        'subtype_name_placeholder': 'Nom (ex: ONG, Ecole...)',
        'ok': 'OK',
        'save_all_settings': 'Enregistrer tous les paramètres',
        'setup_incomplete_warning': 'Veuillez configurer les paramètres obligatoires de votre église pour continuer.',
        'settings_load_error': 'Impossible de charger les paramètres',
        'role_name_required': 'Le nom du rôle est requis.',
        'role_created_success': 'Rôle créé avec succès !',
        'role_creation_error': 'Erreur lors de la création du rôle.',
        'role_deleted': 'Rôle supprimé.',
        'role_delete_error': 'Erreur lors de la suppression du rôle.',
        'contact_type_added': 'Type de contact ajouté',
        'contact_type_delete_error': "Erreur lors de l'ajout",
        'type_deleted': 'Type supprimé',
        'subtype_added': 'Sous-type ajouté',
        'subtype_delete_success': 'Sous-type supprimé',
        'image_upload_success': 'Image téléchargée avec succès !',
        'image_format_error': 'Format non supporté. Utilisez JPG, PNG ou WEBP.',
        'image_size_error': 'Le fichier est trop lourd. La limite est de 5MB.',
        'upload_error': "Erreur lors du téléchargement de l'image.",
        'image_removed': 'Image retirée !',
        'settings_saved_success': 'Paramètres enregistrés avec succès !',
        'admin_panel': 'Panel Administration',
        'global_config_desc': 'Configuration globale de la plateforme',
        'return_dashboard': 'Retour au Dashboard',
        'complete_setup_hint': 'Complétez la configuration pour accéder au dashboard',
        'warning': 'Attention',
        'success': 'Succès',
        // Search Builder
        'op_equals': '= (égal)',
        'op_not_equals': '≠ (différent)',
        'op_greater_than': '> (supérieur)',
        'op_less_than': '< (inférieur)',
        'op_greater_equal': '>= (sup. ou égal)',
        'op_less_equal': '<= (inf. ou égal)',
        'op_contains': 'Contient',
        'op_starts_with': 'Commence par',
        'op_ends_with': 'Termine par',
        'op_in': 'Dans la liste (a,b,c)',
        'op_today': "Aujourd'hui",
        'op_this_month': "Ce mois-ci",
        'op_this_year': "Cette année",
        'op_date_range': "Période personnalisée",
        'op_after': 'Après le...',
        'op_before': 'Avant le...',
        'op_exact_day': 'Au jour près...',
        // Dashboard New Keys
        'search_anything': 'Rechercher...',
        'member_growth': 'Croissance Membres',
        'last_7_days': '7 derniers jours',
        'week': 'Semaine',
        'month': 'Mois',
        'demographics': 'Démographie',
        'recent_activity': 'Activité Récente',
        'this_week': 'Cette semaine',
        'upcoming_events': 'Événements à venir',
        'total_donations': 'Total Dons',
        'upcoming_ceremonies': 'Cérémonies à venir',
        'no_recent_activity': 'Aucune activité récente',
        'id': 'ID',
        'name': 'Nom',
        'type': 'Type',
        'status': 'Statut',
        'pages': 'Pages',
        'main_dashboard': 'Tableau de bord principal',
        'birthdays_this_week': 'Anniversaires de la semaine',
        'no_birthdays_this_week': 'Aucun anniversaire cette semaine',
        'search_members': 'Rechercher un membre...',
        'no_upcoming_events': 'Aucun événement à venir',
        'donation_received': 'Don reçu',
        'from': 'De',
        'no_recent_members': 'Aucun membre récent',
        'view_more': 'Voir plus',
        'recent_activity': 'Activité Récente',
        'birthdays_management': 'Gestion des Anniversaires',
        'birthdays_desc': 'Retrouvez les anniversaires à venir, filtrez par date et exportez la liste.',
        'birthdays_report': 'Rapport Anniversaires',
        'celebration_date': 'Date de Célébration',
        'age_turning': 'Âge',
        'no_birthdays_found': 'Aucun anniversaire trouvé pour cette période.',
        'today': "Aujourd'hui",
        'this_month': "Ce mois-ci",
        'last_month': "Le mois dernier",
        'next_month': "Le mois prochain",
        'this_quarter': "Ce trimestre",
        'this_semester': "Ce semestre",
        'fiscal_year': "L'année fiscale",
        'last_year': "L'année dernière",
        'send_to_all_today': "Envoyer à tous (aujourd'hui)",
        'send_birthday_wish': "Souhaiter un anniversaire",
        'message_filtered': 'Message à la liste filtrée',
        'message_all': 'Message groupé',
        'send_bulk_message': 'Envoyer un message groupé',
        'placeholder_hint': 'Astuce: Utilisez {firstName} pour personnaliser automatiquement le prénom.',
        'members_targeted': 'membres ciblés',
        'happy_birthday_all': 'Joyeux Anniversaire à tous !',
        'happy_birthday': 'Joyeux Anniversaire !',
        'birthday_message_template': 'Bonjour {firstName}, toute la communauté vous souhaite un joyeux anniversaire !',
        'broadcast_all': 'Diffuser à tous',
        'group_name': 'Nom du Groupe',
        'responsible': 'Responsable',
        'meeting': 'Réunion',
        'groups_list': 'Liste des Groupes',
        'back_to_dashboard': 'Retour au Dashboard',
        'groups_ministries': 'Groupes & Ministères',
        'new_group': 'Nouveau Groupe',
        'total_groups': 'Total Groupes',
        'ministries': 'Ministères',
        'cells': 'Cellules',
        'departments': 'Départements',
        'all_types': 'Tous les types',
        'view_members': 'Voir les membres',
        'add_group_ministry': 'Ajouter un Groupe/Ministère',
        'group_name_placeholder': 'Ex: Chorale, Jeunesse...',
        'group_description_placeholder': 'Description du groupe...',
        'group_type_ministry': 'Ministère',
        'group_type_cell': 'Cellule',
        'group_type_department': 'Département',
        'group_type_other': 'Autre',
        'responsible_name': 'Nom du Responsable',
        'responsible_name_placeholder': 'Nom complet du responsable',
        'meeting_day': 'Jour de réunion',
        'meeting_day_placeholder': 'Ex: Lundi, Mercredi...',
        'meeting_time': 'Heure de réunion',
        'add_member_to_group': 'Ajouter un membre au groupe',
        'choose_member': 'Choisir un membre...',
        'role_in_group': 'Rôle dans le groupe',
        'adhesion_date': "Date d'adhésion",
        'leader': 'Responsable',
        'assistant': 'Assistant',
        'delete_group_title': 'Supprimer le groupe',
        'delete_group_confirm': 'Êtes-vous sûr de vouloir supprimer ce groupe ? Cette action est irréversible.',
        'group_created_success': 'Groupe créé avec succès',
        'group_updated_success': 'Groupe mis à jour avec succès',
        'group_deleted_success': 'Groupe supprimé avec succès',
        'group_logo': 'Logo du Groupe',
        'group_logo_desc': 'Logo du groupe (Image)',
        'group_charter': 'Charte du Groupe',
        'group_charter_desc': 'Charte du groupe (Document/PDF)',
        'download_charter': 'Télécharger la charte',
        'view_charter': 'Voir la charte',
        'room_calendar': 'Calendrier de la salle',
        'room_occupied': 'Occupée',
        'room_free': 'Libre',
        'room_availability': 'Disponibilité',
        'member_added_success': 'Membre ajouté au groupe avec succès',
        'add_member': 'Ajouter un membre',
        'back_to_list': 'Retour à la liste',
        'member_count': 'Membres',
        'delete_error': 'Erreur lors de la suppression',
        'operation_error': "Erreur lors de l'opération",
        'Members management': 'Gestion des Membres',
        'Members desc': 'Gérez les membres de votre église, leur statut et leurs informations.',
        'no_members_found': 'Aucun membre trouvé.',
        'confirm_delete_attachment': 'Voulez-vous vraiment supprimer cet attachement ?',
        'attachment_instr': 'Uploadez des certificats, photos ou documents légaux directement sur le profil.',
        'manage_files': 'Gestion des documents',
        'summary_note': 'Note de synthèse',
        'no_history_found': 'Aucun historique trouvé',
        'no_communication_recorded': 'Aucune communication enregistrée',
        'no_donations_recorded': 'Aucun don enregistré',
        'no_participation_recorded': 'Aucune participation enregistrée',
        'no_attachments_found': 'Aucun attachement trouvé',
        'no_categories_found': 'Aucune catégorie trouvée',
        'change_category': 'Changer la catégorie',
        'passing_category_to': 'Passage de la catégorie vers',
        'online_presence': 'Présence en ligne',
        'personal_info': 'Informations personnelles',
        'contact_information': 'Coordonnées',
        'phone_call': 'Appel tél.',
        'visit': 'Visite',
        'add_note': 'Ajouter une note',
        'add_action': 'Ajouter une action',
        'action_type': "Type d'action",
        'note_title_placeholder': 'Ex: Appel de suivi',
        'note_desc_placeholder': 'Détails de la note...',
        'action_desc_placeholder': "Décrivez l'action effectuée...",
        'tithes': 'Dîmes',
        'donation_history': 'Historique des dons',
        'sunday_school_history': 'Historique École Dominicale',
        'group_membership': 'Appartenance aux Groupes',
        'requests': 'Demandes',
        'open': 'Ouverte',
        'resolved': 'Résolue',
        'add_donation': 'Ajouter un don',
        'donation_notes_placeholder': 'Note sur ce don (optionnel)...',
        'subject': 'Sujet',
        'sent_by': 'Envoyé par',
        'communication_history': 'Historique des communications',
        'attachments': 'Attachements',
        'relationships_network': 'Relations & Réseau',
        'sunday_school_history': "Historique École du Dimanche",
        'groups_history': 'Historique des Groupes',
        'no_birthday_found': 'Aucun anniversaire trouvé',
        'nickname': 'Surnom',
        'birth_place': 'Lieu de naissance',
        'primary': 'Primaire',
        'secondary': 'Secondaire',
        'secondary_phone': 'Téléphone secondaire',
        'secondary_email': 'Email secondaire',
        'spouse_name': 'Nom du conjoint',
        'join_date': "Date d'adhésion",
        'entry_date': "Date d'entrée",
        'Member ID': 'ID Membre',
        'member_id': 'ID Membre',
        'social_presence': 'Présence en ligne',
        'instagram': 'Instagram',
        'tiktok': 'TikTok',
        'website': 'Site Web',
        'view_member_properties': 'Voir propriétés du membre',
        'member_properties': 'Propriétés du membre',
        'added_by': 'Ajouté par',
        'date_created': 'Date de création',
        'time_created': 'Heure de création',
        'emergency_email': 'Email d\'urgence',
        'actions': 'Actions',
        'edit': 'Modifier',
        'delete': 'Supprimer',
        'view_details': 'Voir détails',
        'all_status': 'Tous les statuts',
        'all_categories': 'Toutes les catégories',
        'collapse_list': 'Réduire la liste',
        'list_view': 'Liste',
        'grid_view': 'Grille',
        'role_status': 'Rôle/Statut',
        'no_country': 'Pas de pays',
        'no_email': 'Pas d\'email',
        'no_number': 'Pas de numéro',
        'send_message': 'Envoyer un message',
        'gender_short_m': 'H',
        'gender_short_f': 'F',
        'events_management': 'Gestion des Événements',
        'events_desc': 'Gérez les cultes, prières, concerts et conférences de votre communauté.',
        'new_event': 'Nouvel Événement',
        'total_events': 'Total Événements',
        'past_events': 'Écoulés',
        'total_participants': 'Participants',
        'list_view': 'Liste',
        'grid_view': 'Grille',
        'view_all': 'Voir tous',
        'show_less': 'Réduire',
        'event': 'Événement',
        'no_events_found': 'Aucun événement trouvé.',
        'event_deleted_success': 'Événement supprimé avec succès.',
        'event_updated_success': 'Événement mis à jour avec succès.',
        'event_created_success': 'Événement créé avec succès.',
        'delete_event_title': 'Supprimer l\'événement',
        'delete_event_confirm': 'Êtes-vous sûr de vouloir supprimer cet événement ?',
        'events_list': 'Liste des événements',
        'events_report': 'Rapport des événements',
        'participants_count': 'Participants',
        'upcoming': 'À venir',
        'past': 'Écoulés',
        'download_day': 'Télécharger le jour',
        'download_week': 'Télécharger la semaine',
        'download_month': 'Télécharger le mois',
        'download_year': 'Télécharger l\'année',
        'unavailability': 'Indisponibilité',
        'export_schedule': 'Exporter l\'horaire',
        'edit_group': 'Modifier le groupe',
        'modifier_infos_groupe': 'Modifier les infos du groupe',
        'schedule_name': 'Nom de l\'horaire',
        'today_sentence': 'Aujourd\'hui',
        'this_week_sentence': 'Cette semaine',
        'this_month_sentence': 'Ce mois-ci',
        'this_quarter_sentence': 'Ce trimestre',
        'this_year_sentence': 'L\'année',
        'download_label': 'Télécharger :',
        'first_name': 'Prénom',
        'last_name': 'Nom',
        'description': 'Description',
        'wants_membership': 'Veut devenir membre?',
        'view_status': 'Statut de vue',
        'not_viewed': 'Non vue',
        'viewed': 'Vue',
        'become_member': 'Devenir membre',
        'mark_as_viewed': 'Marquer comme vue',
        'convert_to_member_confirm': 'Êtes-vous sûr de vouloir convertir ce visiteur en membre?',
        'conversion_success': 'Visiteur converti en membre avec succès',
        'export_to_excel': 'Exporter vers Excel',
        'search_visitors': 'Rechercher des visiteurs',
        'search_placeholder': 'Nom, email, téléphone...',
        'date_range': 'Plage de dates',
        'from_date': 'Du',
        'to_date': 'Au',
        'search': 'Rechercher',
        'yes': 'Oui',
        'no': 'Non',
        'description_placeholder': 'Note du visiteur...',
        'visitor_marked_viewed': 'Visiteur marqué comme vu',
        'visitor_created': 'Visiteur créé avec succès',
        'error_converting_visitor': 'Erreur lors de la conversion',
        'confirm': 'Confirmer',
        'review_visitor': 'Revoir le visiteur',
        'review_notes_placeholder': 'Ajouter des notes sur cette visite...',
        'membership_interest_question': 'Le visiteur veut-il devenir membre?',
        'save_and_mark_viewed': 'Marquer comme vu',
        'visitor_reviewed': 'Visiteur revu avec succès',
        'visitor_conversion_info': 'Complétez les informations manquantes pour convertir ce visiteur en membre',
        'new_visitors': 'Nouveaux visiteurs',
        'former_visitors': 'Anciens visiteurs',
        'show_all': 'Voir tous',
        'show_less': 'Voir moins',
        'welcome_to': 'Bienvenue sur',
        'login_to_space': 'Connectez-vous à votre espace',
        'email_placeholder': 'pastè@egliz.com',
        'password_placeholder': '••••••••',
        'forgot_password': 'Mot de passe oublié ?',
        'login_btn': 'Se connecter',
        'no_account': 'Pas encore de compte ?',
        'register_here': 'Enregistrez votre église ici',
        'back_home': 'Retour à l\'accueil',
        // Member Profile - Alert & Contact Keys
        'add_alert': 'Ajouter une alerte',
        'member_alert': 'Alerte membre',
        'alert_message_placeholder': 'Ex: Membre inactif depuis quelques mois, à contacter...',
        'alert_added_success': 'Alerte ajoutée avec succès',
        'alert_deleted_success': 'Alerte supprimée',
        'error_adding_alert': "Erreur lors de l'ajout de l'alerte",
        'no_alerts': 'Aucune alerte',
        'delete_alert': 'Supprimer cette alerte',
        'work_contacts': 'Coordonnées professionnelles',
        'emergency_contacts': "Contact d'urgence",
        'work_address': 'Adresse de travail',
        'work_email': 'Email professionnel',
        'work_phone': 'Téléphone professionnel',
        'emergency_contact_name': 'Nom du contact d\'urgence',
        'emergency_phone': 'Téléphone d\'urgence',
        'constituent_summary': 'Informations personnelles',
        'constituent_id': 'Membre ID',
        'none_found': 'Aucun résultat.',
        'notes': 'Notes',
        'actions': 'Actions',
        'relationships': 'Relations',
        'timeline': 'Chronologie',
        'giving': 'Dons',
        'giving_history': 'Historique des dons',
        'no_online_presence': 'Aucune présence en ligne trouvée',
        'no_recent_timeline': 'Aucune activité chronologique récente.',
        'primary_addressee': 'Destinataire principal',
        'primary_salutation': 'Salutation principale',
        'primary_envelope': 'Enveloppe principale',
        'name_formats': 'Formats de noms',
        'add_attachment': 'Ajouter un document',
        'add_note_placeholder': 'Pourquoi ce changement ?',
        'merge': 'Fusionner avec un autre enregistrement',
        'apply_workflow': 'Appliquer un flux de travail',
        'modified_by': 'Modifié par',
        'level': 'Niveau',
        'role': 'Rôle',
        'years_old': 'ans',
        'member_requests': 'Gestion des Demandes',
        'my_requests': 'Mes Demandes',
        'submit_request': 'Soumettre une demande',
        'new_request': 'Nouvelle demande',
        'request_title': 'Titre / Objet',
        'request_type': 'Type de demande',
        'request_description': 'Description détaillée',
        'internal_note': 'Note interne',
        'request_status': 'Statut',
        'assigned_to': 'Responsable du suivi',
        'status_not_viewed': 'Non vue',
        'status_viewed': 'Vue',
        'status_processed': 'Traitée',
        'status_follow_up': 'Suivi approfondi',
        'request_marriage': 'Demande de mariage',
        'request_baptism': 'Demande de baptême',
        'request_transfer': 'Demande de transfert',
        'request_member_card': 'Demande de carte membre',
        'request_support': 'Demande de support',
        'request_ministry': 'Intégration dans un ministère',
        'request_info': 'Demande d\'information',
        'request_reservation': 'Demande de réservation',
        'request_meeting': 'Planification de rencontre',
        'request_other': 'Autre demande',
        'request_created_success': 'Demande soumise avec succès !',
        'request_updated_success': 'Demande mise à jour avec succès.',
        'request_deleted_success': 'Demande supprimée.',
        'filter_by_type': 'Filtrer par type',
        'filter_by_status': 'Filtrer par statut',
        'search_requests': 'Rechercher une demande...',
        'no_requests': 'Aucune demande trouvée.',
        'request_details': 'Détails de la demande',
        'update_status': 'Mettre à jour le statut',
        'add_internal_note': 'Ajouter une note interne',
        'assigned_to_me': 'M\'attribuer cette demande',
        'history_log': 'Historique & Journalisation',
        'describe_your_request': 'Veuillez décrire votre demande en détail...',
        'manage_your_requests_desc': 'Suivez vos demandes et communiquez avec l\'église',
        'donation': 'Don',
        'unread': 'non lue',
        'all_up_to_date': 'Tout est à jour',
        'sunday_school_classes': 'Classes dominicales',
        'edit_post': 'Modifier la publication',
        'new_post': 'Nouvelle publication',
        'share_with_community': 'Partagez avec votre communauté',
        'post_category': 'Catégorie de post',
        'visible_to': 'Visible pour (Destinataire)',
        'entire_church': "Toute l'Église",
        'all_elyon360': 'Tout Elyon360',
        'precise_target': 'Cible précise',
        'select_category_placeholder': 'Sélectionner une catégorie...',
        'post_title_optional': 'Titre (Optionnel)',
        'post_title_placeholder': 'Donnez un titre percutant...',
        'your_message': 'Votre message',
        'what_to_say_today': "Que souhaitez-vous dire aujourd'hui ?",
        'change_image': "Changer l'image",
        'add_photo': 'Ajouter une photo',
        'saving_post': 'Enregistrement...',
        'publish_message': 'Publier un message',
        'view_all_notifications': 'Voir toutes les notifications',
        'new_notifications_count': 'nouvelle(s)',
        'admin_space': 'Espace administrateur',
        'card_id_official_desc': "Cette carte est votre document d'identité officiel. Notez qu'elle ne peut pas être modifiée par l'utilisateur.",
        'front_side': 'Côté recto',
        'back_side': 'Côté verso',
        'card_status': 'Statut de la carte',
        'member_id_identification': 'Identification member ID',
        'declare_lost_card': 'Déclarer une carte perdue',
        'declare_stolen_card': 'Déclarer une carte volée',
        'no_publication': 'Aucune publication',
        'community_posts': 'Publications de la communauté',
        'filter_by': 'Filtrer par :',
        'load_older_posts': 'Charger les publications anciennes',
        'no_publication_yet': "Aucune publication pour l'instant.",
        'my_member_card': 'Ma carte membre',
        'card_id_desc': 'Votre identification officielle au sein de la communauté.',
        'no_active_card': 'Aucune carte active',
        'card_not_generated_desc': "Votre carte de membre n'a pas encore été générée ou est en attente d'activation. Si vous n'en avez jamais fait la demande, vous pouvez le faire maintenant.",
        'status_member': 'Membre',
        'since': 'Depuis',
        'personal_information': 'Informations personnelles',
        'gender_label': 'Sexe',
        'birth_place': 'Lieu de naissance',
        'marital_status_label': 'État civil',
        'spouse_name': 'Nom conjoint',
        'member_category': 'Catégorie de membre',
        'birth_date': 'Date de naissance',
        'member_code': 'Code membre',
        'welcome_member_space': 'Bienvenue dans votre espace membre',
        'follow_your_latest_activity': 'Suivez vos derniers mouvements',
        'view_all_history': "Voir tout l'historique détaillé",
        'no_recent_activity': 'Aucune activité enregistrée',
        'declare_defective_card': 'Déclaration de Carte Défectueuse',
        'my_card_is_defective': 'Ma carte est défectueuse',
        'donation_history': 'Historique des Dons',
        'total': 'Total',
        'no_donation_recorded': 'Aucun don enregistré',
        'groups': 'Groupes',
        'ministries': 'Ministères',
        'no_ministry_desc': 'Vous ne faites partie d\'un ministère.',
        'add_note_optional': 'Souhaitez-vous ajouter une remarque ? (Optionnel)',
        'provide_justification': 'Veuillez fournir une raison justifiable pour cette déclaration s\'il vous plaît (Obligatoire).',
        'additional_explanations': 'Explications supplémentaires',
        'required': 'Obligatoire',
        'optional': 'Optionnel',
        'front_detailed_view': 'Vue Détaillée Recto',
        'back_detailed_view': 'Vue Détaillée Verso',
        'connected_as': 'Connecté comme',
        'click_to_switch': 'Cliquez pour basculer',
        'no_notifications': 'Aucune notification',
        'no_sunday_school_desc': 'Vous n\'êtes inscrit à aucune classe dominicale.',
        'no_group_desc': 'Vous n\'êtes membre d\'aucun groupe.',
        'no_description': 'Pas de description.',
        'click_to_close': "Cliquez n'importe où pour fermer",
        'additional_note_placeholder': 'Remarque additionnelle...',
        'justification_placeholder': 'Indiquez les circonstances justificatives (ex: perdue le 15, rayée)...',
    },
    en: {
        'dashboard': 'Dashboard',
        'contacts': 'Contacts',
        'members': 'Members',
        'visitors': 'Visitors',
        'organizations': 'Organizations',
        'events': 'Events',
        'groups': 'Groups',
        'finances': 'Finances',
        'income': 'Income',
        'expenses': 'Expenses',
        'budgets': 'Budgets',
        'sunday_school': 'Sunday School',
        'overview': 'Overview',
        'classes': 'Classes',
        'class_details': 'Class Details',
        'participant_code': 'Participant Code',
        'participant_name': 'Participant Name',
        'member_role': 'Member Role',
        'criteria': 'Criteria',
        'active_only': 'Active Only',
        'monitors': 'Monitors',
        'attendance_rate': 'Attendance Rate',
        'new_members': 'New Members',
        'transitions_due': 'Transitions Due',
        'monitor_coverage': 'Monitor Coverage',
        'reports_status': 'Reports Status',
        'recent_activity': 'Recent Activity',
        'near_transition': 'Near Transition',
        'recommended_class': 'Recommended Class',
        'transition_reason': 'Reason',
        'total_active_classes': 'Active Classes',
        'attendance_trend': 'Attendance Trend',
        'class_distribution': 'Class Distribution',
        'alerts_notifications': 'Alerts & Notifications',
        'pending_reports': 'Pending Reports',
        'weekly_report': 'Weekly Report',
        'general_info': 'General Information',
        'meeting_date': 'Meeting Date',
        'meeting_title': 'Meeting Title',
        'lesson_details': 'Lesson Details',
        'lesson_title_form': 'Lesson Taught',
        'total_lesson_points': 'Total Lesson Points',
        'covered_lesson_points': 'Points Covered',
        'golden_text': 'Golden Text',
        'attendance_list': 'Attendance List',
        'lesson_metrics': 'Participation Metrics',
        'bible_count': 'No. of Bibles',
        'hymnal_count': 'No. of Hymnals',
        'offering_collected': 'Offering Collected',
        'feedback_and_expectations': 'Feedback & Expectations',
        'monitor_notes': 'Monitor Notes',
        'monitor_expectations': 'Monitor Expectations',
        'participant_expectations': 'Participant Expectations',
        'submit_report': 'Submit Report',
        'spiritual_progress': 'Spiritual Progress',
        'presence_list': 'Presence List',
        'new_weekly_report': 'New Weekly Report',
        'report_submitted_success': 'Report submitted successfully!',
        'reports': 'Reports',
        'reports_history': 'Reports History',
        'no_reports_found': 'No reports found',
        'lesson_title': 'Lesson Title',
        'lesson_completion': 'Lesson Completion',
        'participation_metrics': 'Participation Metrics',
        'feedback': 'Feedback & Observations',
        'submitted_by': 'Submitted by',
        'report_not_found': 'Report not found',
        'offering': 'Offering',
        'new_class': 'New Class',
        'edit_class': 'Edit Class',
        'create_new_class': 'Create New Class',
        'class_name': 'Class Name',
        'age_group': 'Age Group',
        'min_age': 'Min Age',
        'max_age': 'Max Age',
        'distribution_by_class': 'Distribution by Class',
        'assign_monitor': 'Assign Monitor',
        'choose_member': 'Choose Member',
        'monitor_assigned_success': 'Monitor assigned successfully',
        'class_created_success': 'Class created successfully',
        'class_updated_success': 'Class updated successfully',
        'baptismal_status': 'Baptismal Status',
        'baptized': 'Baptized',
        'not_baptized': 'Not Baptized',
        'candidate': 'Candidate',
        'any': 'Any',
        'inventory': 'Inventory',
        'ceremonies': 'Ceremonies',
        'settings': 'Settings',
        'logout': 'Logout',
        'hello': 'Hello',
        'admin': 'Admin',
        'configuration_required': 'Configuration Required',
        'setup_msg': 'Before you start managing your church, you must configure basic information.',
        'setup_btn': 'Configure now',
        'total_members': 'Total Members',
        'new_member': 'New Member',
        'search': 'Search',
        'status': 'Status',
        'active': 'Active',
        'inactive': 'Inactive',
        'country': 'Country',
        'schedule_name': 'Schedule Name',
        'category': 'Category',
        'reset': 'Reset',
        'export_pdf': 'Export to PDF',
        'export_excel': 'Export to Excel',
        'export': 'Export',
        'export_options': 'Export Options',
        'select_export_fields': 'Select the fields you want to include in your report.',
        'all': 'All',
        'age': 'Age',
        'email': 'Email',
        'primary': 'Primary',
        'secondary': 'Secondary',
        'secondary_phone': 'Secondary phone',
        'secondary_email': 'Secondary email',
        'income_overview': 'Income Overview',
        'distribution_by_type': 'Distribution by Type',
        'recent_transactions': 'Recent Transactions',
        'view_all': 'View all',
        'income_vs_expenses': 'Income vs Expenses',
        'total_income': 'Total Income',
        'total_expenses': 'Total Expenses',
        'balance': 'Balance',
        'transactions': 'Transactions',
        'new_donation': 'New Donation',
        'amount': 'Amount',
        'date': 'Date',
        'member': 'Member',
        'type': 'Type',
        'payment_method': 'Payment Method',
        'note': 'Note',
        'save': 'Save',
        'cancel': 'Cancel',
        'loading': 'Loading...',
        'no_data': 'No data found.',
        'total_revenue': 'Total Revenue',
        'this_month_short': 'this month',
        'monthly_analysis': 'MONTHLY ANALYSIS',
        'growth_insight': 'Positive growth this month',
        'view_details': 'View details',
        'anonymous': 'Anonymous',
        'confirmed': 'Confirmed',
        'currency': 'Currency',
        'select_member_placeholder': 'Select a member (Anonymous by default)',
        'no_results': 'No results',
        'first_name': 'First Name',
        'last_name': 'Last Name',
        'gender_label': 'Gender',
        'masculine': 'Masculine',
        'feminine': 'Feminine',
        'birth_date': 'Birth Date',
        'marital_status_label': 'Marital Status',
        'single': 'Single',
        'married': 'Married',
        'divorced': 'Divorced',
        'widowed': 'Widowed',
        'contact_info': 'Contact Info',
        'phone': 'Phone',
        'address': 'Address',
        'city': 'City',
        'nif_cin_label': 'NIF / CIN',
        'photo': 'Photo',
        'upload_file': 'Upload',
        'use_url': 'Use URL',
        'edit_member': 'Edit Member',
        'fill_info_desc': 'Fill in the information below',
        'identity_personnel': 'Identity & Personnel',
        'select': 'Select',
        'recent_members_added': 'Last members added',
        'visitors_desc': 'Manage visitors and their integration into the community.',
        'full_name': 'Full Name',
        'status_integrated': 'Integration',
        'no_visitors': 'No visitors found.',
        'visitor_info_desc': 'Basic visitor information',
        'status_integrated_label': 'Integrated',
        'status_contacted_label': 'Contacted',
        'status_visited_label': 'Visited',
        'management_desc': 'Manage partner and affiliated organizations.',
        'new_org': 'New Organization',
        'edit_org': 'Edit Organization',
        'org_info_desc': 'Organization details and classification',
        'identification_classification': 'Identification & Classification',
        'org_name': 'Organization Name',
        'org_name_placeholder': 'Ex: Foundation, School, NGO...',
        'select_category': 'Select a category',
        'contact_location': 'Contact & Location',
        'official_email': 'Official Email',
        'address_placeholder': 'Full address...',
        'no_orgs': 'No organizations found.',
        'org_list_title': 'Organizations List',
        'quick_insight': 'Quick Insight',
        'system_health': 'System Health',
        'users_online': 'Users Online',
        'server_load': 'Server Load',
        'last_backup': 'Last Backup',
        'take_action': 'Take Action',
        'deposited_on_account': 'Deposited on account?',
        'select_account_placeholder': 'Select account...',
        'no_account_found_currency': 'No account found for currency',
        'deposit_date_label': 'Deposit date',
        'deposited_by': 'Deposited by',
        'confirm_donation': 'Confirm Donation',
        'data_load_error': 'Unable to load data. Check if server is running. ',
        'account_created_success': 'Account created successfully!',
        'creation_error': 'Error during creation',
        'select_bank_account_error': 'Please select a bank account.',
        'select_donations_error': 'Please select at least one donation to deposit.',
        'select_date_error': 'Please select the deposit date.',
        'select_depositor_error': 'Please select the person who made the deposit.',
        'overview': 'Overview',
        'accounts_and_treasury': 'Accounts & Treasury',
        'administrator': 'Administrator',
        'cancel_btn': 'Cancel',
        'update_btn': 'Update',
        'save_btn': 'Save',
        'saving': 'Saving...',
        'elyonsys_360': 'ELYONSYS 360',
        'error_saving': 'Error during registration',
        'first_name_placeholder': 'Ex: John',
        'last_name_placeholder': 'Ex: Doe',
        'optional': 'Optional',
        'error_saving_expense': 'Error saving expense',
        'insufficient_funds': 'Insufficient funds',
        'fonds_insufficient_disp': 'Insufficient funds. Available: ',
        'error_creating_budget': 'Error creating budget',
        'budgets_desc': 'Management and tracking of budget envelopes.',
        'full_list': 'Full List',
        'export_list': 'Export list',
        'search_budget': '🔍 Search budget...',
        'all_statuses': 'All statuses',
        'consumed': 'Consumed',
        'no_budgets_found': 'No budgets found for these criteria.',
        'allocate_funds': 'Allocation of church funds',
        'source_account': 'Source Account',
        'available_for_this_budget': 'Available for this budget',
        'budget_name_label': 'Budget name',
        'allocated_amount': 'Allocated amount',
        'bank_account_source': 'Source Bank Account',
        'select_source_account': 'Select source account',
        'start_date': 'Start date',
        'end_date': 'End date',
        'budget_objectives_placeholder': 'Objectives of this budget...',
        'create_budget_btn': 'Create budget',
        'detailed_report': 'Detailed Report',
        'print_pdf': 'Print / PDF',
        'excel': 'Excel',
        'budget_total': 'Total Budget',
        'expenses_detail': 'Expenses Detail',
        'loading_expenses': 'Loading expenses...',
        'no_expenses_found': 'No expenses found for this budget.',
        'total_expenses_label': 'Total Expenses:',
        'prepared_by': 'Prepared by:',
        'responsible_pastor': 'Responsible / Pastor:',
        'generated_by_on': 'Generated by ElyonSys 360 on ',
        'no_active_budgets': 'No active budgets at the moment.',
        'active_budgets': 'Active Budgets',
        'view_report': 'View report',
        'used': 'Used',
        'remaining_text': 'remaining',
        'period': 'Period',
        'report': 'Report',
        'expenses_desc': 'Track money outflows and manage your costs.',
        'budget_expenses_desc': 'List of expenses allocated to this specific budget.',
        'view_all_expenses': 'View all expenses',
        'new_expense': 'New Expense',
        'no_expenses_for_budget': 'No expenses recorded for this budget.',
        'no_category': 'No category',
        'out_of_budget': 'Out of Budget',
        'new_expense_desc': 'Recording a fund outflow',
        'available_in_budget': 'Available in this budget',
        'expense_reason_label': 'Expense reason',
        'expense_reason_placeholder': 'Ex: Electricity bill, Furniture purchase...',
        'impute_to_budget': 'Allocate to budget',
        'select_budget': 'Select a budget',
        'funds_deduction_notice': 'Funds will be deducted from the budget\'s source account.',
        'category_placeholder': 'Ex: Administration, Social...',
        'budget_exceeded_error': 'Amount exceeds budget. Action impossible.',
        'validate_expense_btn': 'Validate Expense',
        'contacts_dashboard': 'Contacts Dashboard',
        'overview_stats': 'Overview and Statistics',
        'search_member': 'Search member',
        'church_growth': 'Church Growth',
        'last_6_months': 'Last 6 Months',
        'by_gender': 'By Gender',
        'men': 'Men',
        'women': 'Women',
        'by_category': 'By Category',
        'unclassified': 'Unclassified',
        'by_status': 'By Status',
        'traveling': 'Traveling',
        'deceased': 'Deceased',
        'transferred': 'Transferred',
        'abandoned': 'Abandoned',
        'recent_additions': 'Recent Additions',
        'view_all_members': 'View All Members',
        'error_saving_note': 'Error saving note',
        'error_updating_photo': 'Error updating photo',
        'error_updating_status': 'Error updating status',
        'error_updating_type': 'Error updating type',
        'member_not_found': 'Member Not Found',
        'back': 'Back',
        'view_large': 'View Large',
        'change_photo': 'Change Photo',
        'modify_summary': 'Modify Summary',
        'add_summary_note': 'Add Summary',
        'modify': 'Modify',
        'mark_as': 'Mark as...',
        'change_type': 'Change Type',
        'no_types_available': 'No types available',
        'change_status': 'Change Status',
        'passing_status_to': 'Changing status to',
        'effective_date': 'Effective Date',
        'confirm': 'Confirm',
        'passing_category_to': 'Changing category to',
        'info': 'Info',
        'personal_information': 'Personal Information',
        'gender': 'Gender',
        'birth': 'Birth',
        'civil_status': 'Civil Status',
        'nif_cin': 'NIF / CIN',
        'age': 'Age',
        'years': 'years',
        'geo': 'Geo',
        'contact_localization': 'Contact & Localization',
        'no_number': 'No number',
        'no_address_recorded': 'No address recorded',
        'history_activities': 'History & Activities',
        'relationships_network': 'Relationships & Network',
        'donations_history': 'Donations History',
        'payment_date': 'Payment Date',
        'donation_type': 'Donation Type',
        'total_amount': 'Total Amount',
        'no_donations_recorded': 'No donations recorded',
        'membership_groups': 'Membership Groups',
        'no_groups_found': 'No groups found',
        'ceremonies_attended': 'Ceremonies Attended',
        'no_ceremonies_recorded': 'No ceremonies recorded',
        'tithe_regulator': 'Tithe Regulator',
        'events_attended': 'Events Attended',
        'no_participation_recorded': 'No participation recorded',
        'status_history': 'Status History',
        'changed_by': 'Changed by',
        'system': 'System',
        'no_history_available': 'No history available',
        'category_history': 'Category History',
        'close': 'Close',
        'good_morning': 'Good Morning',
        'good_afternoon': 'Good Afternoon',
        'good_evening': 'Good Evening',
        'dashboard_welcome_desc': 'Here is an overview of your community activity today.',
        'insight_desc': 'You have activities to check this week.',
        '2h_ago': '2h ago',
        'management_desc': 'External entities management',
        'new_org': 'Organization',
        'org_list_title': 'Organizations List',
        'no_orgs': 'No organizations recorded.',
        'edit_org': 'Edit Organization',
        'org_info_desc': 'Manage structure information and contacts.',
        'identification_classification': 'Identification & Classification',
        'org_name': 'Organization Name',
        'org_name_placeholder': 'Ex: Church of Prophecy',
        'select_category': 'Select...',
        'official_email': 'Official Email',
        'address_hq': 'HQ Address',
        'address_placeholder': 'Street, City, Country',
        'visitors_desc': 'Manage people visiting your church.',
        'new_visitor': 'New Visitor',
        'full_name': 'Full Name',
        'status_integrated': 'Integration',
        'status_contacted': 'Contacted',
        'no_visitors': 'No visitors recorded.',
        'visitor_info_desc': 'Add a new visitor to your database.',
        'note_placeholder_summary': 'Summary notes...',
        'member_details': 'Member Details',
        'baptized': 'Baptized',
        'category_changed_on': 'Category changed on',
        'no_recent_members': 'No recent members.',
        'loading_config': 'Loading configuration...',
        'church_settings_website': 'Church Settings - Website',
        'identity_appearance_comm': 'Identity, Appearance & Communication',
        'basic_info': 'Basic Information',
        'identity_global_desc': 'Global identity and description',
        'church_name': 'Church Name',
        'church_name_placeholder': 'Ex: Church of Prophecy',
        'acronym_label': 'Acronym / Initialism',
        'subdomain_label': 'Subdomain (Unique ID)',
        'owner_email_label': 'Owner Email (Admin)',
        'description_who_we_are': 'Description (Who we are)',
        'appearance': 'Appearance',
        'visual_identity_desc': 'Visual and identity of the platform',
        'hero_image_label': 'Hero Image (Home background)',
        'hero_image_placeholder': 'Image URL or upload one...',
        'upload': 'Upload',
        'hero_image_hint': 'Recommended: 1920x1080px, under 5MB',
        'current_preview': 'Current Preview',
        'remove_image': 'Remove Image',
        'mission_title_label': 'Mission Title or Summary',
        'mission_title_placeholder': 'Ex: Carrying the Light of the world.',
        'mission_desc_label': 'Mission Description',
        'mission_bg_image': 'Background Image (Mission)',
        'vision_title_label': 'Vision Title or Summary',
        'vision_title_placeholder': 'Ex: Building a generation united by faith.',
        'vision_desc_label': 'Vision Description',
        'vision_bg_image': 'Background Image (Vision)',
        'our_values': 'Our Values',
        'values_placeholder': 'List of your values (ex: Love, Faith, Excellence)...',
        'values_image': 'Values Image',
        'design_tip': 'Design Tip',
        'values_image_tip': 'The values image will appear next to the text on your home page. Use an image that illustrates the spirit of your community or a montage of your key activities.',
        'pastoral_team': 'Pastoral Team',
        'leadership_members': 'Leadership members',
        'pastoral_team_json_desc': 'JSON format to list your team. Soon, a simplified management interface will be available.',
        'service_schedules': 'Service Schedules',
        'weekly_appointments': 'Your weekly appointments',
        'schedules_json_desc': 'Define your schedules for display on the public site. (Required for public site)',
        'social_links_and_links': 'Social Links & Links',
        'online_presence_live': 'Online presence and live services',
        'platform_name_placeholder': 'Ex: YouTube, Facebook',
        'live_service_link_label': 'Live Service Link (Full URL)',
        'url_placeholder': 'https://www.youtube.com/live/...',
        'copy': 'COPY',
        'paste': 'PASTE',
        'link_copied': 'Link copied!',
        'link_pasted': 'Link pasted!',
        'paste_error': 'Unable to read clipboard. Paste manually with Ctrl+V.',
        'live_link_hint': 'If this link is filled, an "Online" button will appear on your public home page.',
        'recent_activities': 'Recent Activities',
        'public_site_news': 'Public site news',
        'activities_json_desc': 'JSON format to list your activities. Soon, a simplified management interface will be available.',
        'contact_location': 'Contact & Location',
        'coords_physical_address': 'Coordinates and physical address',
        'full_address': 'Full Address',
        'address_placeholder_miracles': 'Ex: 123 Miracles St',
        'city_placeholder_pap': 'Ex: Port-au-Prince',
        'contact_email': 'Contact Email',
        'save_section': 'Save this section',
        'finance_settings': 'Finance Settings',
        'currencies_donations_accounting': 'Currencies, Donations & Accounting',
        'currencies_and_money': 'Currencies & Money',
        'accepted_currencies_management': 'Accepted currencies management',
        'mandatory_currencies_error': 'HTG and USD are mandatory and cannot be deleted.',
        'cannot_delete_currency_balance': 'Cannot delete: Non-zero balance.',
        'currency_code_placeholder': 'Code (ex: EUR, CAD)',
        'add_currency': 'Add Currency',
        'donation_types_settings': 'Donation Types',
        'custom_categories': 'Custom categories',
        'donation_category_placeholder': 'Category name (ex: Construction)',
        'new_type': 'New Type',
        'payment_methods_settings': 'Payment Methods',
        'accepted_payment_methods': 'Accepted payment methods',
        'payment_method_placeholder': 'Method name (ex: MonCash)',
        'new_method': 'New Method',
        'users_roles_management': 'Users & Roles Management',
        'roles_permissions_desc': 'Create custom roles with specific permissions',
        'permissions_granted': 'permissions granted',
        'new_role': 'New Role',
        'create_role': 'Create Role',
        'role_name_label': 'Role Name (ex: Secretary)',
        'role_name_placeholder': 'Enter role name...',
        'permissions_access': 'Permissions & Access',
        'save_role': 'Save Role',
        'contact_classification': 'Contact Classification',
        'custom_types_subtypes': 'Custom Types & Subtypes',
        'global_types': 'Global Types',
        'new_type_placeholder': 'New type (ex: Partner)',
        'add': 'Add',
        'contact_subtypes': 'Contact Subtypes',
        'no_subtypes_defined': 'No subtypes defined',
        'add_subtype': 'Add Subtype',
        'select_type_placeholder': 'Select a Type...',
        'subtype_name_placeholder': 'Name (ex: NGO, School...)',
        'ok': 'OK',
        'save_all_settings': 'Save all settings',
        'setup_incomplete_warning': 'Please configure your church\'s mandatory settings to continue.',
        'settings_load_error': 'Unable to load settings',
        'role_name_required': 'Role name is required.',
        'role_created_success': 'Role created successfully!',
        'role_creation_error': 'Error creating role.',
        'role_deleted': 'Role deleted.',
        'role_delete_error': 'Error deleting role.',
        'contact_type_added': 'Contact type added',
        'contact_type_delete_error': 'Error during addition',
        'type_deleted': 'Type deleted',
        'subtype_added': 'Subtype added',
        'subtype_delete_success': 'Subtype deleted',
        'image_upload_success': 'Image uploaded successfully!',
        'image_format_error': 'Unsupported format. Use JPG, PNG or WEBP.',
        'image_size_error': 'File is too heavy. Limit is 5MB.',
        'upload_error': 'Error uploading image.',
        'image_removed': 'Image removed!',
        'settings_saved_success': 'Settings saved successfully!',
        'admin_panel': 'Administration Panel',
        'global_config_desc': 'Global platform configuration',
        'return_dashboard': 'Return to Dashboard',
        'complete_setup_hint': 'Complete configuration to access the dashboard',
        'warning': 'Warning',
        'success': 'Success',
        // Dashboard New Keys
        'search_anything': 'Search anything...',
        'member_growth': 'Member Growth',
        'last_7_days': 'Last 7 Days',
        'week': 'Week',
        'month': 'Month',
        'demographics': 'Demographics',
        'recent_activity': 'Recent Activity',
        'this_week': 'This Week',
        'upcoming_events': 'Upcoming Events',
        'total_donations': 'Total Donations',
        'upcoming_ceremonies': 'Upcoming Ceremonies',
        'no_recent_activity': 'No recent activity',
        'id': 'ID',
        'name': 'Name',
        'type': 'Type',
        'status': 'Status',
        'pages': 'Pages',
        'main_dashboard': 'Main Dashboard',
        'birthdays_this_week': 'Birthdays of the week',
        'no_birthdays_this_week': 'No birthdays this week',
        'search_members': 'Search member...',
        'no_upcoming_events': 'No upcoming events',
        'donation_received': 'Donation Received',
        'from': 'From',
        'no_recent_members': 'No recent members',
        'view_more': 'View more',
        'birthdays_management': 'Birthdays Management',
        'birthdays_desc': 'Find upcoming birthdays, filter by date and export the list.',
        'birthdays_report': 'Birthdays Report',
        'celebration_date': 'Celebration Date',
        'age_turning': 'Age',
        'no_birthdays_found': 'No birthdays found for this period.',
        'today': 'Today',
        'this_month': 'This month',
        'last_month': 'Last month',
        'next_month': 'Next month',
        'this_quarter': 'This quarter',
        'this_semester': 'This semester',
        'fiscal_year': 'Fiscal year',
        'last_year': 'Last year',
        'send_to_all_today': 'Send to all today',
        'send_birthday_wish': 'Send birthday wish',
        'message_filtered': 'Message to filtered list',
        'message_all': 'Bulk Message',
        'send_bulk_message': 'Send Bulk Message',
        'placeholder_hint': 'Tip: Use {firstName} to automatically personalize the first name.',
        'members_targeted': 'members targeted',
        'happy_birthday_all': 'Happy Birthday to all!',
        'happy_birthday': 'Happy Birthday!',
        'birthday_message_template': 'Hello {firstName}, the whole community wishes you a happy birthday!',
        'broadcast_all': 'Broadcast to all',
        'group_name': 'Group Name',
        'responsible': 'Responsible',
        'meeting': 'Meeting',
        'groups_list': 'Groups List',
        'back_to_dashboard': 'Back to Dashboard',
        'groups_ministries': 'Groups & Ministries',
        'new_group': 'New Group',
        'total_groups': 'Total Groups',
        'ministries': 'Ministries',
        'cells': 'Cells',
        'departments': 'Departments',
        'all_types': 'All types',
        'view_members': 'View members',
        'add_group_ministry': 'Add Group/Ministry',
        'group_name_placeholder': 'Ex: Choir, Youth...',
        'group_description_placeholder': 'Group description...',
        'group_type_ministry': 'Ministry',
        'group_type_cell': 'Cell',
        'group_type_department': 'Department',
        'group_type_other': 'Other',
        'responsible_name': 'Responsible Name',
        'responsible_name_placeholder': 'Full name of the responsible',
        'meeting_day': 'Meeting day',
        'meeting_day_placeholder': 'Ex: Monday, Wednesday...',
        'meeting_time': 'Meeting time',
        'add_member_to_group': 'Add member to group',
        'choose_member': 'Choose a member...',
        'role_in_group': 'Role in group',
        'adhesion_date': 'Adhesion date',
        'leader': 'Leader',
        'assistant': 'Assistant',
        'delete_group_title': 'Delete Group',
        'delete_group_confirm': 'Are you sure you want to delete this group? This action is irreversible.',
        'group_created_success': 'Group created successfully',
        'group_updated_success': 'Group updated successfully',
        'group_deleted_success': 'Group deleted successfully',
        'group_logo': 'Group Logo',
        'group_logo_desc': 'Group Logo (Image)',
        'group_charter': 'Group Charter',
        'group_charter_desc': 'Group Charter (Document/PDF)',
        'download_charter': 'Download Charter',
        'view_charter': 'View Charter',
        'room_calendar': 'Room Calendar',
        'room_occupied': 'Occupied',
        'room_free': 'Free',
        'room_availability': 'Availability',
        'member_added_success': 'Member added to group successfully',
        'add_member': 'Add member',
        'back_to_list': 'Back to list',
        'member_count': 'Members',
        'delete_error': 'Delete error',
        'operation_error': 'Operation error',
        'Members management': 'Members Management',
        'Members desc': 'Manage your church members, their status and information.',
        'no_members_found': 'No members found.',
        'confirm_delete_attachment': 'Are you sure you want to delete this attachment?',
        'attachment_instr': 'Upload certificates, photos or legal documents directly to the profile.',
        'manage_files': 'Document Management',
        'summary_note': 'Summary Note',
        'no_history_found': 'No history found',
        'no_communication_recorded': 'No communication recorded',
        'no_donations_recorded': 'No donations recorded',
        'no_participation_recorded': 'No participation recorded',
        'no_attachments_found': 'No attachments found',
        'no_categories_found': 'No categories found',
        'change_category': 'Change Category',
        'passing_category_to': 'Changing category to',
        'online_presence': 'Online Presence',
        'personal_info': 'Personal Information',
        'contact_information': 'Contact Information',
        'phone_call': 'Phone call',
        'visit': 'Visit',
        'add_note': 'Add Note',
        'add_action': 'Add Action',
        'action_type': 'Action Type',
        'note_title_placeholder': 'Ex: Follow-up call',
        'note_desc_placeholder': 'Note details...',
        'action_desc_placeholder': 'Describe the action performed...',
        'tithes': 'Tithes',
        'donation_history': 'Donation History',
        'sunday_school_history': 'Sunday School History',
        'group_membership': 'Group Membership',
        'requests': 'Requests',
        'open': 'Open',
        'resolved': 'Resolved',
        'add_donation': 'Add Donation',
        'donation_notes_placeholder': 'Note about this donation (optional)...',
        'subject': 'Subject',
        'sent_by': 'Sent by',
        'communication_history': 'Communication History',
        'attachments': 'Attachments',
        'relationships_network': 'Relationships & Network',
        'sunday_school_history': 'Sunday School History',
        'groups_history': 'Groups History',
        'no_birthday_found': 'No birthdays found',
        'nickname': 'Nickname',
        'birth_place': 'Birth Place',
        'spouse_name': 'Spouse Name',
        'join_date': 'Join Date',
        'entry_date': 'Entry Date',
        'Member ID': 'Member ID',
        'member_id': 'Member ID',
        'social_presence': 'Social Presence',
        'instagram': 'Instagram',
        'tiktok': 'TikTok',
        'website': 'Website',
        'view_member_properties': 'View member properties',
        'member_properties': 'Member Properties',
        'added_by': 'Added by',
        'date_created': 'Date Created',
        'time_created': 'Time Created',
        'emergency_email': 'Emergency Email',
        'actions': 'Actions',
        'edit': 'Edit',
        'delete': 'Delete',
        'view_details': 'View details',
        'all_status': 'All status',
        'all_categories': 'All categories',
        'collapse_list': 'Collapse list',
        'list_view': 'List',
        'grid_view': 'Grid',
        'role_status': 'Role/Status',
        'no_country': 'No country',
        'no_email': 'No email',
        'no_number': 'No number',
        'send_message': 'Send Message',
        'gender_short_m': 'M',
        'gender_short_f': 'F',
        'events_management': 'Events Management',
        'events_desc': 'Manage services, prayers, concerts and conferences of your community.',
        'new_event': 'New Event',
        'total_events': 'Total Events',
        'past_events': 'Past',
        'total_participants': 'Participants',
        'list_view': 'List',
        'grid_view': 'Grid',
        'view_all': 'View all',
        'show_less': 'Show less',
        'event': 'Event',
        'no_events_found': 'No events found.',
        'event_deleted_success': 'Event deleted successfully.',
        'event_updated_success': 'Event updated successfully.',
        'event_created_success': 'Event created successfully.',
        'delete_event_title': 'Delete Event',
        'delete_event_confirm': 'Are you sure you want to delete this event?',
        'events_list': 'Events List',
        'events_report': 'Events Report',
        'participants_count': 'Participants',
        'upcoming': 'Upcoming',
        'past': 'Past',
        'download_day': 'Download day',
        'download_week': 'Download week',
        'download_month': 'Download month',
        'download_year': 'Download year',
        'unavailability': 'Unavailability',
        'export_schedule': 'Export Schedule',
        'edit_group': 'Edit Group',
        'modifier_infos_groupe': 'Edit Group Info',
        'today_sentence': 'Today',
        'this_week_sentence': 'This week',
        'this_month_sentence': 'This month',
        'this_quarter_sentence': 'This quarter',
        'this_year_sentence': 'This year',
        'download_label': 'Download :',
        'first_name': 'First Name',
        'last_name': 'Last Name',
        'description': 'Description',
        'wants_membership': 'Wants to become member?',
        'view_status': 'View Status',
        'not_viewed': 'Not Viewed',
        'viewed': 'Viewed',
        'become_member': 'Become Member',
        'mark_as_viewed': 'Mark as Viewed',
        'convert_to_member_confirm': 'Are you sure you want to convert this visitor to a member?',
        'conversion_success': 'Visitor successfully converted to member',
        'export_to_excel': 'Export to Excel',
        'search_visitors': 'Search visitors',
        'search_placeholder': 'Name, email, phone...',
        'date_range': 'Date Range',
        'from_date': 'From',
        'to_date': 'To',
        'search': 'Search',
        'yes': 'Yes',
        'no': 'No',
        'description_placeholder': 'Visitor note...',
        'visitor_marked_viewed': 'Visitor marked as viewed',
        'visitor_created': 'Visitor created successfully',
        'error_converting_visitor': 'Error converting visitor',
        'confirm': 'Confirm',
        'review_visitor': 'Review Visitor',
        'review_notes_placeholder': 'Add notes about this visit...',
        'membership_interest_question': 'Does the visitor want to become a member?',
        'save_and_mark_viewed': 'Mark as Viewed',
        'visitor_reviewed': 'Visitor successfully reviewed',
        'visitor_conversion_info': 'Complete the missing information to convert this visitor to a member',
        'new_visitors': 'New Visitors',
        'former_visitors': 'Former Visitors',
        'show_all': 'Show All',
        'show_less': 'Show Less',
        'welcome_to': 'Welcome to',
        'login_to_space': 'Log in to your space',
        'email_placeholder': 'pastor@church.com',
        'password_placeholder': '••••••••',
        'forgot_password': 'Forgot password?',
        'login_btn': 'Log In',
        'no_account': "Don't have an account?",
        'register_here': 'Register your church here',
        'back_home': 'Back to Home',
        // Member Profile - Alert & Contact Keys
        'add_alert': 'Add alert',
        'member_alert': 'Member alert',
        'alert_message_placeholder': 'Ex: Inactive member for a few months, needs follow-up...',
        'alert_added_success': 'Alert added successfully',
        'alert_deleted_success': 'Alert deleted',
        'error_adding_alert': 'Error adding alert',
        'no_alerts': 'No alerts',
        'delete_alert': 'Delete this alert',
        'work_contacts': 'Work contacts',
        'emergency_contacts': 'Emergency contact',
        'work_address': 'Work address',
        'work_email': 'Professional email',
        'work_phone': 'Professional phone',
        'emergency_contact_name': 'Emergency contact name',
        'emergency_phone': 'Emergency phone',
        'constituent_summary': 'Personal information',
        'constituent_id': 'Member ID',
        'none_found': 'None found.',
        'notes': 'Notes',
        'actions': 'Actions',
        'relationships': 'Relationships',
        'timeline': 'Timeline',
        'giving': 'Giving',
        'giving_history': 'Giving history',
        'donation_history': 'Donation history',
        'no_online_presence': 'No online presence found',
        'no_recent_timeline': 'No recent timeline activities.',
        'primary_addressee': 'Primary Addressee',
        'primary_salutation': 'Primary Salutation',
        'primary_envelope': 'Primary Envelope',
        'name_formats': 'Name formats',
        'add_attachment': 'Add attachment',
        'add_note_placeholder': 'Why this change?',
        'merge': 'Merge into another record',
        'apply_workflow': 'Apply workflow',
        'modified_by': 'Modified by',
        'level': 'Level',
        'role': 'Role',
        'years_old': 'years old',
        // Search Builder
        'op_equals': '= (equals)',
        'op_not_equals': '≠ (different)',
        'op_greater_than': '> (greater than)',
        'op_less_than': '< (less than)',
        'op_greater_equal': '>= (greater or equal)',
        'op_less_equal': '<= (less or equal)',
        'op_contains': 'Contains',
        'op_starts_with': 'Starts with',
        'op_ends_with': 'Ends with',
        'op_in': 'In list (a,b,c)',
        'op_today': 'Today',
        'op_this_month': 'This month',
        'op_this_year': 'This year',
        'op_date_range': 'Custom date range',
        'op_after': 'After...',
        'op_before': 'Before...',
        'op_exact_day': 'Exact day...',
        'query_architect_pro': 'Query Architect Pro',
        'relational_explorer': 'Advanced Search',
        'explorer_subtitle': 'Joins · Advanced Filters · Export',
        'my_models': 'My Models',
        'save_btn': 'Save',
        'data_source': 'Data Source',
        'choose_a_table': 'Choose a table...',
        'joins': 'Joins',
        'column_selection': 'Column Selection',
        'clear': 'Clear',
        'all': 'All',
        'sorted_by': 'Sorted by',
        'no_sorting': 'No sorting',
        'descending': 'Descending',
        'ascending': 'Ascending',
        'new_filter': 'New Filter',
        'dynamic_filters': 'Dynamic Filters',
        'select_a_field': 'Select a field...',
        'choose_value': 'Choose a value...',
        'enter_value': 'Enter value...',
        'start': 'Start',
        'end': 'End',
        'find_now': 'Find Now',
        'searching': 'Searching...',
        'export_as': 'Export as',
        'results': 'Results',
        'no_results_yet': 'No results yet. Execute a search to see data.',
        'my_saved_models': 'My Saved Models',
        'manage_search_configs': 'Manage your custom search configurations',
        'search_by_name': 'Search by name...',
        'no_models_found': 'No models found',
        'by_admin': 'By Main Admin',
        'cols_abbr': 'cols.',
        'filter_abbr': 'filt.',
        'created_on': 'Created on',
        'load_model_arrow': 'Load →',
        'save_title': 'Save Query',
        'save_description': 'Save this query for later use',
        'query_name': 'Query Name',
        'query_placeholder': 'Ex: Donations Q1...',
        'save_action': 'Save',
        'confirm_delete_model': 'Are you sure you want to delete this model?',
        'model_deleted': 'Model deleted',
        'give_config_name': 'Please give a name to this configuration',
        'config_saved': 'Configuration saved!',
        'loaded': 'Loaded',
        'results_found': 'result(s) found',
        'member_requests': 'Member Requests Management',
        'my_requests': 'My Requests',
        'submit_request': 'Submit a Request',
        'new_request': 'New Request',
        'request_title': 'Title / Subject',
        'request_type': 'Request Type',
        'request_description': 'Detailed Description',
        'internal_note': 'Internal Note',
        'request_status': 'Status',
        'assigned_to': 'Assigned To',
        'status_not_viewed': 'Not Viewed',
        'status_viewed': 'Viewed',
        'status_processed': 'Processed',
        'status_follow_up': 'Follow-up',
        'request_marriage': 'Marriage Request',
        'request_baptism': 'Baptism Request',
        'request_transfer': 'Transfer Request',
        'request_member_card': 'Member Card Request',
        'request_support': 'Support Request',
        'request_ministry': 'Ministry Integration',
        'request_info': 'Information Request',
        'request_reservation': 'Reservation Request',
        'request_meeting': 'Meeting Planning',
        'request_other': 'Other Request',
        'request_created_success': 'Request submitted successfully!',
        'request_updated_success': 'Request updated successfully.',
        'request_deleted_success': 'Request deleted.',
        'filter_by_type': 'Filter by type',
        'filter_by_status': 'Filter by status',
        'search_requests': 'Search requests...',
        'no_requests': 'No requests found.',
        'request_details': 'Request Details',
        'update_status': 'Update Status',
        'add_internal_note': 'Add Internal Note',
        'assigned_to_me': 'Assign to me',
        'history_log': 'History & Logging',
        'describe_your_request': 'Please describe your request in detail...',
        'manage_your_requests_desc': 'Track your requests and communicate with the church',
        'donation': 'Donation',
        'unread': 'unread',
        'all_up_to_date': 'All up to date',
        'sunday_school_classes': 'Sunday School Classes',
        'edit_post': 'Edit Post',
        'new_post': 'New Post',
        'share_with_community': 'Share with your community',
        'post_category': 'Post Category',
        'visible_to': 'Visible to (Recipient)',
        'entire_church': 'Entire Church',
        'all_elyon360': 'All Elyon360',
        'precise_target': 'Precise Target',
        'select_category_placeholder': 'Select a category...',
        'post_title_optional': 'Title (Optional)',
        'post_title_placeholder': 'Give a striking title...',
        'your_message': 'Your Message',
        'what_to_say_today': 'What do you want to say today?',
        'change_image': 'Change Image',
        'add_photo': 'Add a Photo',
        'saving_post': 'Saving...',
        'publish_message': 'Publish a message',
        'view_all_notifications': 'View all notifications',
        'new_notifications_count': 'new',
        'admin_space': 'Admin Space',
        'no_notifications': 'No notifications',
        'no_sunday_school_desc': 'You are not enrolled in any Sunday school classes.',
        'no_group_desc': 'You are not a member of any group.',
        'group': 'Group',
        'no_description': 'No description.',
        'no_recent_activity': 'No recent activity recorded',
        'declare_lost_card': 'Declare Lost Card',
        'declare_stolen_card': 'Declare Stolen Card',
        'declare_defective_card': 'Declare Defective Card',
        'my_card_is_defective': 'My card is defective',
        'donation_history': 'Donation History',
        'total': 'Total',
        'no_donation_recorded': 'No donation recorded',
        'groups': 'Groups',
        'ministries': 'Ministries',
        'no_ministry_desc': 'You are not part of any ministry.',
        'add_note_optional': 'Would you like to add a note? (Optional)',
        'provide_justification': 'Please provide a justifiable reason for this declaration (Required).',
        'additional_explanations': 'Additional Explanations',
        'required': 'Required',
        'optional': 'Optional',
        'front_detailed_view': 'Front Detailed View',
        'back_detailed_view': 'Back Detailed View',
        'connected_as': 'Connected as',
        'click_to_switch': 'Click to switch',
        'hello': 'Hello',
        'click_to_close': 'Click anywhere to close',
        'additional_note_placeholder': 'Additional note...',
        'justification_placeholder': 'Indicate justificatory circumstances (e.g., lost on the 15th)...',
        'new_notifications_count': 'new',
        'admin_space': 'Admin space',
        'card_id_official_desc': "This card is your official identity document. Note that it cannot be modified by the user.",
        'front_side': 'Front side',
        'back_side': 'Back side',
        'card_status': 'Card status',
        'member_id_identification': 'Member ID identification',
        'declare_lost_card': 'Declare lost card',
        'declare_stolen_card': 'Declare stolen card',
        'no_publication': 'No publication',
        'community_posts': 'Community posts',
        'filter_by': 'Filter by:',
        'load_older_posts': 'Load older posts',
        'no_publication_yet': 'No publication yet.',
        'my_member_card': 'My member card',
        'card_id_desc': 'Your official identification within the community.',
        'no_active_card': 'No active card',
        'card_not_generated_desc': "Your member card has not yet been generated or is awaiting activation. If you have never requested one, you can do so now.",
        'status_member': 'Member',
        'since': 'Since',
        'personal_information': 'Personal information',
        'gender_label': 'Gender',
        'birth_place': 'Birth place',
        'marital_status_label': 'Marital status',
        'spouse_name': 'Spouse name',
        'member_category': 'Member category',
        'birth_date': 'Birth date',
        'member_code': 'Member code',
        'welcome_member_space': 'Welcome to your member space',
        'follow_your_latest_activity': 'Follow your latest movements',
        'view_all_history': 'View all detailed history'
    }
};

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState(localStorage.getItem('app_lang') || 'fr');

    useEffect(() => {
        localStorage.setItem('app_lang', language);
    }, [language]);

    const t = (key, defaultValue) => {
        return translations[language][key] || defaultValue || key;
    };

    const toggleLanguage = () => {
        setLanguage(prev => prev === 'fr' ? 'en' : 'fr');
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
